# Generated by Django 5.2.8 on 2025-11-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_code', models.CharField(max_length=100)),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('push', 'Push Notification')], max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('language', models.CharField(default='en', help_text='Language code (e.g., en, fr, es)', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('required_variables', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'template',
                'indexes': [models.Index(fields=['template_code', 'language', 'is_active'], name='template_templat_57b946_idx')],
                'unique_together': {('template_code', 'version', 'language')},
            },
        ),
    ]
