# Generated by Django 5.2.8 on 2025-11-12 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templatemodel',
            old_name='template_name',
            new_name='template_code',
        ),
        migrations.AlterUniqueTogether(
            name='templatemodel',
            unique_together={('template_code', 'version')},
        ),
    ]
