# Generated by Django 5.2.8 on 2025-11-13 12:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('template_app', '0002_rename_template_name_templatemodel_template_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='templatemodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='templatemodel',
            name='language',
            field=models.CharField(default='en', help_text='Language code (e.g., en, fr, es)', max_length=10),
        ),
        migrations.AddField(
            model_name='templatemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='templatemodel',
            unique_together={('template_code', 'version', 'language')},
        ),
        migrations.AddIndex(
            model_name='templatemodel',
            index=models.Index(fields=['template_code', 'language', 'is_active'], name='template_search_idx'),
        ),
    ]
