# Generated by Django 5.2.8 on 2025-11-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('push_token', models.CharField(blank=True, max_length=255, null=True)),
                ('prefers_email', models.BooleanField(default=True)),
                ('prefers_push', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
